name: newman with trello

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install htmlextra
        run: npm install -g newman_reporter_htmlextra

      # Runs a set of commands using the runners shell
      - name: Run newman 
        run: newman run "trello_collection" -r "cli,json,junit,htmlextra" --global-var "tokentrello=${{secrets.TOKENTRELLO}}" --global-var "appkey=${{secrets.APP_KEY}}" --global-var "urltrello=${{secrets.URLTRELLO}}"
 
      - uses: actions/upload-artifact@v3
        with:
         name: newman report
         path: ./newman
